# node.js configuration
publicDirectoryPath: build/public
publicUriPath: /public

# PostCSS configuration
postcss:
  autoprefixer:
    browsers:
      - '> 1%'
      - 'last 2 versions'
      - 'opera 12.1'
      - 'android 4'
    cascade: true
  svg:
    paths:
      - components/svg
  mixins:
    mixinsDir:
      - components/mixins
